let attendeesList = {
  "countries": [
{
  "attendeeCount": 17,
  "attendees": [
  "kvipond@hubspotpartners.com",
  "nschrack@hubspotpartners.com",
  "rumbel@hubspotpartners.com",
  "pobanner@hubspotpartners.com",
  "kgearn@hubspotpartners.com",
  "llucksom@hubspotpartners.com",
  "dtalas@hubspotpartners.com",
  "fseel@hubspotpartners.com",
  "cmeixner@hubspotpartners.com",
  "ymanvel@hubspotpartners.com",
  "khollard@hubspotpartners.com",
  "jlupien@hubspotpartners.com",
  "cthoman@hubspotpartners.com",
  "oayars@hubspotpartners.com",
  "eenglar@hubspotpartners.com",
  "cbickle@hubspotpartners.com",
  "mjoice@hubspotpartners.com"
  ],
  "name": "Ireland",
  "startDate": "2017-05-21"
},
{
  "attendeeCount": 14,
  "attendees": [
    "cclifton@hubspotpartners.com",
    "jkatynski@hubspotpartners.com",
    "bsur@hubspotpartners.com",
    "lbucciarelli@hubspotpartners.com",
    "sklimkowicz@hubspotpartners.com",
    "bwhitton@hubspotpartners.com",
    "cbrookover@hubspotpartners.com",
    "mkaarlela@hubspotpartners.com",
    "aabeita@hubspotpartners.com",
    "iburlingame@hubspotpartners.com",
    "aturli@hubspotpartners.com",
    "tkeefauver@hubspotpartners.com",
    "tjensrud@hubspotpartners.com",
    "kbeneker@hubspotpartners.com"
  ],
  "name": "United States",
  "startDate": "2017-06-19"
},
{
  "attendeeCount": 17,
  "attendees": [
  "iborris@hubspotpartners.com",
  "caburto@hubspotpartners.com",
  "rbumbray@hubspotpartners.com",
  "rangelini@hubspotpartners.com",
  "hveigel@hubspotpartners.com",
  "jaddesso@hubspotpartners.com",
  "toberst@hubspotpartners.com",
  "gmachenry@hubspotpartners.com",
  "scasini@hubspotpartners.com",
  "mvirrueta@hubspotpartners.com",
  "tjamili@hubspotpartners.com",
  "mgabard@hubspotpartners.com",
  "kburness@hubspotpartners.com",
  "fservidio@hubspotpartners.com",
  "mkorth@hubspotpartners.com",
  "scalcote@hubspotpartners.com",
  "emckearin@hubspotpartners.com"
  ],
  "name": "Spain",
  "startDate": "2017-05-17"
},
{
  "attendeeCount": 17,
  "attendees": [
  "adomek@hubspotpartners.com",
  "dteachman@hubspotpartners.com",
  "msmaller@hubspotpartners.com",
  "kvanis@hubspotpartners.com",
  "cstoots@hubspotpartners.com",
  "lbersamin@hubspotpartners.com",
  "dluckner@hubspotpartners.com",
  "jlantto@hubspotpartners.com",
  "talman@hubspotpartners.com",
  "ldelmastro@hubspotpartners.com",
  "cembrey@hubspotpartners.com",
  "drobison@hubspotpartners.com",
  "lpyun@hubspotpartners.com",
  "mmellis@hubspotpartners.com",
  "regure@hubspotpartners.com",
  "tcatello@hubspotpartners.com",
  "tbotkins@hubspotpartners.com"
  ],
  "name": "Mexico",
  "startDate": "2017-05-14"
},
{
  "attendeeCount": 17,
  "attendees": [
    "tbreath@hubspotpartners.com",
    "vcresto@hubspotpartners.com",
    "ykempel@hubspotpartners.com",
    "tkeer@hubspotpartners.com",
    "qlenherr@hubspotpartners.com",
    "emaurey@hubspotpartners.com",
    "cwhiteside@hubspotpartners.com",
    "chathaway@hubspotpartners.com",
    "lclakley@hubspotpartners.com",
    "ddegeest@hubspotpartners.com",
    "jbueckers@hubspotpartners.com",
    "dgazaille@hubspotpartners.com",
    "ftebo@hubspotpartners.com",
    "cboiser@hubspotpartners.com",
    "rramoutar@hubspotpartners.com",
    "kjorgensen@hubspotpartners.com",
    "grhames@hubspotpartners.com"
  ],
  "name": "Canada",
  "startDate": "2017-06-17"
},
{
  "attendeeCount": 14,
  "attendees": [
    "mrebello@hubspotpartners.com",
    "dmunning@hubspotpartners.com",
    "gpavlovic@hubspotpartners.com",
    "dmigliorisi@hubspotpartners.com",
    "jdubose@hubspotpartners.com",
    "abassani@hubspotpartners.com",
    "mvierps@hubspotpartners.com",
    "alamper@hubspotpartners.com",
    "tfeichter@hubspotpartners.com",
    "lclaude@hubspotpartners.com",
    "eberkey@hubspotpartners.com",
    "icalais@hubspotpartners.com",
    "lerenrich@hubspotpartners.com",
    "snowling@hubspotpartners.com"
  ],
  "name": "Singapore",
  "startDate": "2017-06-26"
},
{
  "attendeeCount": 14,
  "attendees": [
    "cciervo@hubspotpartners.com",
    "amandiola@hubspotpartners.com",
    "bdross@hubspotpartners.com",
    "atrigueiro@hubspotpartners.com",
    "ecurtner@hubspotpartners.com",
    "nmccarney@hubspotpartners.com",
    "rigtanloc@hubspotpartners.com",
    "obomberger@hubspotpartners.com",
    "kmeadowcroft@hubspotpartners.com",
    "jence@hubspotpartners.com",
    "jmaita@hubspotpartners.com",
    "bkratochvil@hubspotpartners.com",
    "htiedeman@hubspotpartners.com",
    "mpetrucci@hubspotpartners.com",
  ],
  "name": "Japan",
  "startDate": "2017-05-22"
},
{
  "attendeeCount": 15,
  "attendees": [
    "tguida@hubspotpartners.com",
    "bkostenko@hubspotpartners.com",
    "nrodrigeuz@hubspotpartners.com",
    "spascale@hubspotpartners.com",
    "bhudec@hubspotpartners.com",
    "rhebrank@hubspotpartners.com",
    "ssolecki@hubspotpartners.com",
    "tmosier@hubspotpartners.com",
    "mguthmiller@hubspotpartners.com",
    "nhatzell@hubspotpartners.com",
    "rborys@hubspotpartners.com",
    "aloewenthal@hubspotpartners.com",
    "jdelpino@hubspotpartners.com",
    "abozard@hubspotpartners.com",
    "aheuring@hubspotpartners.com",
  ],
  "name": "United Kingdom",
  "startDate": "2017-05-07"
},
{
  "attendeeCount": 14,
  "attendees": [
    "mcuzman@hubspotpartners.com",
    "tjoh@hubspotpartners.com",
    "kaperges@hubspotpartners.com",
    "ssupplee@hubspotpartners.com",
    "spracht@hubspotpartners.com",
    "sovall@hubspotpartners.com",
    "alukander@hubspotpartners.com",
    "ecarbone@hubspotpartners.com",
    "jschlimmer@hubspotpartners.com",
    "moquin@hubspotpartners.com",
    "jnagg@hubspotpartners.com",
    "kcoldren@hubspotpartners.com",
    "mhockins@hubspotpartners.com",
    "jveal@hubspotpartners.com",
  ],
  "name": "France",
  "startDate": "2017-05-03"
}
  ]
}